version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PORT=5002
    ports:
      - 5002:5002
    networks:
      - local-network

  client:
    environment:
      - REACT_APP_SERVER_PORT=5002
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
